// Auto-generated by: npx supabase gen types typescript --project-id wurnsxgvmpabfchzeyrz > src/lib/database.types.ts
// Regenerate after every schema migration.
// This stub keeps TypeScript happy until the first real generation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
