import { createFileRoute } from "@tanstack/react-router";
import { SiteNav } from "@/components/SiteNav";
import { COMPANY } from "@/lib/company";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — School Field Trip Busing" },
      { name: "description", content: "Terms of Service for booking school field trip transportation." },
      { property: "og:title", content: "Terms of Service" },
      { property: "og:description", content: "Terms governing use of our school field trip booking platform." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <SiteNav />
      <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <span className="rounded-full bg-accent/30 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">
          Legal
        </span>
        <h1 className="mt-4 text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: June 2026</p>

        <div className="mt-8 space-y-6 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p className="mt-2">
              By using the {COMPANY.name} booking platform ("Service") you agree to these Terms.
              If you are booking on behalf of a school or organization, you confirm you have
              authority to bind that organization.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">2. Bookings & Quotes</h2>
            <p className="mt-2">
              Quotes generated by the Service are estimates based on the information you
              provide. Final pricing is confirmed in writing prior to dispatch. A booking is
              not confirmed until {COMPANY.name} sends a written confirmation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">3. Cancellations & Changes</h2>
            <p className="mt-2">
              Cancellations made less than 48 hours before pickup may be subject to a fee up
              to the full trip amount. Routing changes on the day of travel may incur
              additional hourly charges.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">4. Conduct & Safety</h2>
            <p className="mt-2">
              Schools are responsible for adequate adult supervision aboard the bus. Drivers
              may refuse to depart or may end a trip early if passenger conduct creates an
              unsafe condition. Damage caused by passengers will be billed to the school.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">5. Liability</h2>
            <p className="mt-2">
              {COMPANY.name} carries commercial liability insurance as required by the
              Province of British Columbia. To the maximum extent permitted by law, our
              liability for any claim arising out of a trip is limited to the amount paid for
              that trip.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">6. Payment</h2>
            <p className="mt-2">
              Invoices are due within 30 days of issue unless other terms are agreed in
              writing. Overdue accounts may be charged interest at 1.5% per month.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">7. Changes to these Terms</h2>
            <p className="mt-2">
              We may update these Terms from time to time. Material changes will be
              communicated to active member schools by email.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">8. Contact</h2>
            <p className="mt-2">
              Questions about these Terms? Contact {COMPANY.name} via the contact details on
              our home page.
            </p>
          </section>

          <p className="text-xs italic">
            This is a starter Terms of Service drafted for {COMPANY.name}. It is not legal
            advice. Have it reviewed by a lawyer before relying on it.
          </p>
        </div>
      </main>
    </div>
  );
}
